
FROM resin/%%RESIN_MACHINE_NAME%%-node:8

RUN apt-get update && npm install @angular/cli -g

WORKDIR /usr/src/app

COPY package.json package.json

RUN JOBS=MAX npm cache verify && npm install --production --unsafe-perm && rm -rf /tmp/*

COPY . ./

ENV INITSYSTEM on

CMD ["npm", "start"]
