
FROM resin/%%RESIN_MACHINE_NAME%%-node:8

RUN apt-get update && npm install @angular/cli -g

WORKDIR /usr/src/app
RUN mkdir -p /usr/src/app/dist

COPY package.json package.json

RUN JOBS=MAX npm install --production --unsafe-perm && npm cache verify && rm -rf /tmp/*
RUN JOBS=MAX npm install @angular-devkit/build-angular @angular/compiler-cli typescript
RUN npm run build
COPY . ./

ENV INITSYSTEM on

CMD ["npm", "start"]
